### ISSUE TITLE
The API path needs updating

### ISSUE THREAD

**Issue by parallax-home** [gregtwallace/certificate-scripts#2]
These example scripts use the old legocerthub API path and syntax, they need updating to comply with the new ones.

**Comment by parallax-home** [comment]
Thanks! Is it also necessary to update the header format from old "apiKey" to the newer "X-API-Key"? Or is the former still supported? I saw you removed the /legocerthub redirect in 0.23.

**Comment by gregtwallace** [comment]
I do not currently have any plan to remove support for either.
