### ISSUE TITLE
cw-proxmox_pve.sh issue

### ISSUE THREAD

**Issue by darwincr** [gregtwallace/certificate-scripts#9]
i tried filling in the gaps in [cw-proxmox_pve.sh](https://github.com/gregtwallace/certificate-scripts/blob/master/cw-proxmox_pve.sh) 

didnt work the old certificate was still exposed

after i updated the example

from
pve_cert="/etc/pve/nodes/$pve_node_name/pve-ssl.pem"
pve_key="/etc/pve/nodes/$pve_node_name/pve-ssl.key"
to
pve_cert="/etc/pve/nodes/$pve_node_name/pveproxy-ssl.pem"
pve_key="/etc/pve/nodes/$pve_node_name/pveproxy-ssl.key"

the script worked

PVE documentation says 

> You have the following options for the certificate used by pveproxy:
>1. By default the node-specific certificate in /etc/pve/nodes/NODENAME/pve-ssl.pem is used. This certificate is signed by the cluster CA and therefore not automatically trusted by browsers and operating systems.
>2. use an externally provided certificate (e.g. signed by a commercial CA).
>3. use ACME (Let’s Encrypt) to get a trusted certificate with automatic renewal, this is also integrated in the Proxmox VE API and web interface.
>For options 2 and 3 the file /etc/pve/local/pveproxy-ssl.pem is used.

>Do not replace or manually modify the automatically generated node certificate files in /etc/pve/local/pve-ssl.pem and /etc/pve/local/pve-ssl.key (...)

**Comment by gregtwallace** [comment]
Thanks, I have fixed this.
